import express from "express";
export const dashboardRouter = express.Router();
import * as dashboardController from "../controllers/dashboard.controller.js";
import { v2 as cloudinary } from "cloudinary";
import { CloudinaryStorage } from "multer-storage-cloudinary";
import multer from "multer";
import path from "path";
import { generalLimit, authLimit } from "./middleware/rateLimiter.js";
import { validate } from "./middleware/validate.js";
import { authenticateToken } from "./middleware/authenticateToken.js";
import { checkTokens } from "./middleware/checkTokens.js";
const prefix = "/dashboard";
cloudinary.config({
  cloud_name: "doigxmzte",
  api_key: "976469476164149",
  api_secret: "pKqVvE8bbqakSRcCQZAjOXqA0oE",
});
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: "imzen",
    allowed_formats: ["webp"],
    transformation: [{ crop: "limit" }],
  },
});
const upload = multer({ storage: storage });
dashboardRouter.get(`/debug-sentry`, dashboardController.debugSentry);
dashboardRouter.get(
  `${prefix}`,
  generalLimit,
  checkTokens,
  dashboardController.getDashboard,
);
dashboardRouter.get(
  `${prefix}/getUserAdmin/:id`,
  authenticateToken,
  dashboardController.getUserAdminById,
);
dashboardRouter.get(
  `${prefix}/updateBanner/:id`,
  authenticateToken,
  dashboardController.getBannerById,
);
dashboardRouter.get(
  `${prefix}/updateNotify/:id`,
  authenticateToken,
  dashboardController.getUpdateNotify,
);
dashboardRouter.get(
  `${prefix}/updateBN/:id`,
  authenticateToken,
  dashboardController.getUpdateBanner,
);
dashboardRouter.get(
  `${prefix}/updateFuncApp/:id`,
  authenticateToken,
  dashboardController.getupdateFuncApp,
);
dashboardRouter.get(
  `${prefix}/updateApp/:id`,
  authenticateToken,
  dashboardController.getUpdateApp,
);
dashboardRouter.get(
  `${prefix}/updateFuncDevice/:id`,
  authenticateToken,
  dashboardController.getUploadFuncDevice,
);
dashboardRouter.get(
  `${prefix}/updateDevice/:id`,
  authenticateToken,
  dashboardController.getUpdateDevice,
);
dashboardRouter.get(
  `${prefix}/updateCategoryblogs/:id`,
  authenticateToken,
  dashboardController.getUpdateCategoryblogs,
);
dashboardRouter.get(
  `${prefix}/updateblogs/:id`,
  authenticateToken,
  dashboardController.getUpdateblogs,
);
dashboardRouter.get(
  `${prefix}/editBlogDraft/:id`,
  authenticateToken,
  dashboardController.getEditBlogDraft,
);
dashboardRouter.get(
  `${prefix}/downloadOrder/:id`,
  authenticateToken,
  dashboardController.downloadOrder,
);
dashboardRouter.get(
  `${prefix}/reloadOrder`,
  authenticateToken,
  dashboardController.reloadOrder,
);
dashboardRouter.get(
  `${prefix}/reloadJob/:idAdmin`,
  authenticateToken,
  dashboardController.reloadJob,
);
dashboardRouter.get(
  `${prefix}/updateStatusJob/:idJob`,
  authenticateToken,
  dashboardController.updateStatusJob,
);
dashboardRouter.get(
  `${prefix}/getUpdateJob/:idJob`,
  authenticateToken,
  dashboardController.getUpdateJob,
);
dashboardRouter.post(
  `${prefix}/registerAdmin`,
  authLimit,
  validate,
  authenticateToken,
  dashboardController.postRegisterAdmin,
);
dashboardRouter.post(
  `${prefix}/addCarousel`,
  authenticateToken,
  upload.single("imageCarousel"),
  dashboardController.postCarousel,
);
dashboardRouter.post(
  `${prefix}/addNotify`,
  authenticateToken,
  dashboardController.addNotify,
);
dashboardRouter.post(
  `${prefix}/addBanner`,
  authenticateToken,
  upload.single("imgBanner"),
  dashboardController.addBanner,
);
dashboardRouter.post(
  `${prefix}/listFuncApp`,
  authenticateToken,
  dashboardController.addListFuncApp,
);
dashboardRouter.post(
  `${prefix}/addApp`,
  authenticateToken,
  upload.single("imgApp"),
  dashboardController.addApp,
);
dashboardRouter.post(
  `${prefix}/listFuncDevice`,
  authenticateToken,
  dashboardController.addListFuncDevice,
);
dashboardRouter.post(
  `${prefix}/addDevice`,
  authenticateToken,
  upload.fields([
    { name: "imgDevice", maxCount: 10 },
    { name: "colorImg", maxCount: 10 },
  ]),
  dashboardController.addDevice,
);
dashboardRouter.post(
  `${prefix}/addCategoryblogs`,
  authenticateToken,
  dashboardController.addCategoryblogs,
);
dashboardRouter.post(
  `${prefix}/addblogs/`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.addblogs,
);
dashboardRouter.post(
  `${prefix}/addBlogDraft`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.addBlogDraft,
);
dashboardRouter.post(
  `${prefix}/postDraft/:id`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.postDraft,
);
dashboardRouter.post(
  `${prefix}/uploadImage`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.uploadImage,
);
dashboardRouter.post(
  `${prefix}/addVoucher`,
  authenticateToken,
  upload.single("imgVoucher"),
  dashboardController.addVoucher,
);
dashboardRouter.post(
  `${prefix}/addJob`,
  authenticateToken,
  dashboardController.addJob,
);
dashboardRouter.post(
  `${prefix}/saveMindmap`,
  authenticateToken,
  dashboardController.saveMindmap,
);
dashboardRouter.post(
  `${prefix}/subscribe`,
  authenticateToken,
  dashboardController.subscribeNotification,
);
dashboardRouter.post(
  `${prefix}/resetMFA`,
  authenticateToken,
  dashboardController.resetMFA,
);
dashboardRouter.put(
  `${prefix}/updateAdmin/:idUpdate`,
  authenticateToken,
  dashboardController.putUpdateAdminById,
);
dashboardRouter.put(
  `${prefix}/updatePWAdmin/:idUpdate`,
  authenticateToken,
  dashboardController.putUpdatePWAdmin,
);
dashboardRouter.put(
  `${prefix}/updateCarousel/:id`,
  authenticateToken,
  upload.single("imageCarousel"),
  dashboardController.putUpdateCarousel,
);
dashboardRouter.put(
  `${prefix}/updateNotify/:id`,
  authenticateToken,
  dashboardController.putUpdateNotify,
);
dashboardRouter.put(
  `${prefix}/updateBN/:id`,
  authenticateToken,
  upload.single("imgBanner"),
  dashboardController.putUpdateBN,
);
dashboardRouter.put(
  `${prefix}/updateFuncApp/:id`,
  authenticateToken,
  dashboardController.putUpdateFuncApp,
);
dashboardRouter.put(
  `${prefix}/updateApp/:id`,
  authenticateToken,
  upload.single("imgApp"),
  dashboardController.putUpdateApp,
);
dashboardRouter.put(
  `${prefix}/updateFuncDevice/:id`,
  authenticateToken,
  dashboardController.putUpdateFuncDevice,
);
dashboardRouter.put(
  `${prefix}/updateDevice/:id`,
  authenticateToken,
  upload.fields([
    { name: "imgDevice", maxCount: 10 },
    { name: "colorImg", maxCount: 10 },
  ]),
  dashboardController.putUpdateDevice,
);
dashboardRouter.put(
  `${prefix}/updateCategoryblogs/:id`,
  authenticateToken,
  dashboardController.putUpdateCategoryblogs,
);
dashboardRouter.put(
  `${prefix}/updateblogs/:id`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.putUpdateblogs,
);
dashboardRouter.put(
  `${prefix}/editBlogDraft/:id`,
  authenticateToken,
  upload.single("imgblogs"),
  dashboardController.putEditBlogDraft,
);
dashboardRouter.put(
  `${prefix}/updateOrder`,
  authenticateToken,
  dashboardController.updateOrder,
);
dashboardRouter.put(
  `${prefix}/changeStatusOrders`,
  authenticateToken,
  dashboardController.changeStatusOrders,
);
dashboardRouter.put(
  `${prefix}/importDevice`,
  authenticateToken,
  dashboardController.importDevice,
);
dashboardRouter.put(
  `${prefix}/assignAdmin`,
  authenticateToken,
  dashboardController.assignAdmin,
);
dashboardRouter.put(
  `${prefix}/updateJob`,
  authenticateToken,
  dashboardController.updateJob,
);
dashboardRouter.delete(
  `${prefix}/deleteUserAdmin/:idDelete`,
  authenticateToken,
  dashboardController.deleteUserAdminById,
);
dashboardRouter.delete(
  `${prefix}/deleteImgCarousel/:id`,
  authenticateToken,
  dashboardController.deleteImgCarousel,
);
dashboardRouter.delete(
  `${prefix}/deleteCarousel/:id`,
  authenticateToken,
  dashboardController.deleteCarousel,
);
dashboardRouter.delete(
  `${prefix}/deleteNotify/:id`,
  authenticateToken,
  dashboardController.deleteNotify,
);
dashboardRouter.delete(
  `${prefix}/deleteImgBanner/:id`,
  authenticateToken,
  dashboardController.deleteImgBanner,
);
dashboardRouter.delete(
  `${prefix}/deleteBN/:id`,
  authenticateToken,
  dashboardController.deleteBN,
);
dashboardRouter.delete(
  `${prefix}/deleteFuncApp/:id`,
  authenticateToken,
  dashboardController.deleteFuncApp,
);
dashboardRouter.delete(
  `${prefix}/deleteApp/:id`,
  authenticateToken,
  dashboardController.deleteApp,
);
dashboardRouter.delete(
  `${prefix}/deleteImgApp/:id`,
  authenticateToken,
  dashboardController.deleteImgApp,
);
dashboardRouter.delete(
  `${prefix}/deleteFuncDevice/:id`,
  authenticateToken,
  dashboardController.deleteFuncDevice,
);
dashboardRouter.delete(
  `${prefix}/deleteDevice/:id`,
  authenticateToken,
  dashboardController.deleteDevice,
);
dashboardRouter.delete(
  `${prefix}/deleteImgDevice/:id`,
  authenticateToken,
  dashboardController.deleteImgDevice,
);
dashboardRouter.delete(
  `${prefix}/deleteImgColorDevice/:id`,
  authenticateToken,
  dashboardController.deleteImgColorDevice,
);
dashboardRouter.delete(
  `${prefix}/deleteImgBlog/:id`,
  authenticateToken,
  dashboardController.deleteImgBlog,
);
dashboardRouter.delete(
  `${prefix}/deleteCategoryblogs/:id`,
  authenticateToken,
  dashboardController.deleteCategoryblogs,
);
dashboardRouter.delete(
  `${prefix}/deleteblogs/:id`,
  authenticateToken,
  dashboardController.deleteblogs,
);
dashboardRouter.delete(
  `${prefix}/deleteBlogDraft/:id`,
  authenticateToken,
  dashboardController.deleteBlogDraft,
);
dashboardRouter.delete(
  `${prefix}/deleteJob/:idJob`,
  authenticateToken,
  dashboardController.deleteJob,
);
dashboardRouter.delete(
  `${prefix}/deleteVoucher/:idVoucher`,
  authenticateToken,
  dashboardController.deleteVoucher,
);
